[qart]
use_pattern = false
use_color = false
color_threshold = 0
use_color_tint = false
tint_brightness = 64
qr_version = 11
x_aspect = 1
y_aspect = 1
pad_l = 2
pad_r = 2
content = "Attention Is All You Need."
threshold = 127

[path]
input_path = "example/101798742.jpg"
output_path = "./toqart"
